### ISSUE TITLE
[backend] create setup.sql script

### ISSUE THREAD

**Issue by SelmanKahya** [Kommunity-app/kommunity-backend#5]
it should drop database `community` then create it with new/updated fields.

ilk etapta database'i sql dosyasina export edebiliriz, sonra bunu codebase'e commitleriz. ilerleyen surede bunu otomatize etmemiz gerekecek.

read migrations doc:
http://docs.sequelizejs.com/manual/tutorial/migrations.html

**Comment by MustafaOnurKilinc** [comment]
Done.
