### ISSUE TITLE
[backend] get logged in user's details

### ISSUE THREAD

**Issue by SelmanKahya** [Kommunity-app/kommunity-backend#52]
Bu endpoint kullanici kendi profil sayfasini goruntulemek icin gerekli. (su task'e de bir bak: https://github.com/Kommunity-app/kommunity-backend/issues/51)

giris yapmis kullancinin tum detaylari geri donmeli:

- kullanici adi
- email
- nickname?
- lokasyon?
- sosyal linkleri
- diger `field`lar..

bu yeni endpoint hic bir arguman almamali, login olan kullanici icin zaten middleware'de token'i decode edip id'sine ulasabiliyoruz.

sorularin icin @MustafaOnurKilinc'ya ulasabilirsin.

**Comment by MustafaOnurKilinc** [comment]
#50 içerisinde tamamlandı.
